Fix misleading error message.
redhat-performance/test_tools-wrappers pull request #44
Opened 2024-10-02 08:33 UTC by dvalinrh

An error message indicates fio test.  This is misleading as this tool can be used by many different tests.

2024-10-02 11:54 UTC, frival commented on grab_disks
> +	echo  "Need to have disks to perform desks, non provided."
Um ... I'm just gonna ask.  "desks" and "non" ?

2024-10-02 11:55 UTC, frival reviewed
Entertaining typos.

2024-10-02 13:39 UTC, kdvalin requested changes

2024-10-02 13:39 UTC, kdvalin commented on grab_disks
> +	echo  "Need to have disks to perform disks, none provided."
> Need to have disks to perform disks

Yes this floor is made of floor. 

Maybe something like
```suggestion
	echo  "Need to have disks to perform test, none provided."
```

2024-10-02 16:03 UTC, frival approved these changes
LGTM

2024-10-14 15:41 UTC, kdvalin approved these changes
LGTM

2024-10-14 15:52 UTC, merged