Add code to automatically verify wrappers
redhat-performance/test_tools-wrappers pull request #45
Opened 2024-10-09 08:47 UTC by dvalinrh

2024-11-19 18:48 UTC, kdvalin requested changes

2024-11-19 18:48 UTC, kdvalin commented on validate_line
> +}
How about you add it now? :P

2024-11-19 18:48 UTC, kdvalin commented on validate_line
> +	echo $3
So what's the point of arg 1 and 2 then?

2024-11-19 18:48 UTC, kdvalin commented on validate_line
> +		grep -q ^${value}: $base_results_file
If the string has a period in it I believe you can get around the "needs to match" requirement, since that's used as a placeholder of "Any character"

2024-11-19 18:48 UTC, kdvalin commented on validate_line
> +		grep -q ^${value}: $base_results_file
Same issue, are we intending the period to allow any char in this case?

2024-11-19 18:48 UTC, kdvalin commented on validate_line
> +		fi
Maybe provide a regex value that you just send straight into grep.  Allows some flexibility in future.

2024-12-10 13:52 UTC, dvalinrh commented on general_setup
> +	echo "  --test_verification: Runs the test verification.  Information is in the test_verify file in the tests github"
Add file parameter.

2025-01-13 13:23 UTC, dvalinrh commented
Example of verification file
==============
Required_Systems: intel,amd,arm
fields: T/V:s,N:2,NB:n,P:n,Q:n:Time:n,Gflops:n
test:--iterations 1:base_test_results/base_line
test:--iterations 1 --use_mkl:base_test_results/auto_mkl_results_file
test:--iterations 1 --blis_lib:base_test_results/auto_hpl_base/blis
test:--iterations 1 --resgression:base_test_results/auto_hpl_base/regression
===============
Required_Systems: <future enhancement, when in place will track the archs run on to those required>
fields:  <field name>:<field type>,......
          Known types:
                 s: string
                 sm: string, must match.
                 n: numeric field
test:<options>:<results file to compare against>

2025-02-12 16:47 UTC, kdvalin requested changes
Fix typo

2025-02-12 16:47 UTC, kdvalin commented on sample_verification/verifiction_config/auto_hpl_verify
> +fileds: T/V:s,N:2,NB:n,P:n,Q:n:Time:n,Gflops:n
```suggestion
fields: T/V:s,N:2,NB:n,P:n,Q:n:Time:n,Gflops:n
```

2025-02-13 18:51 UTC, kdvalin commented on sample_verification/README
> +fileds: T/V:s,N:n,NB:n,P:n,Q:n:Time:n,Gflops:n
```suggestion
fields: T/V:s,N:n,NB:n,P:n,Q:n:Time:n,Gflops:n
```

2025-02-19 13:40 UTC, kdvalin approved these changes
LGTM

2025-02-19 13:46 UTC, merged