Add script to convert units to a base value.
redhat-performance/test_tools-wrappers pull request #48
Opened 2024-11-20 12:57 UTC by dvalinrh

Given a unit, convert it to the base.
Time base is nano seconds
Memory base is bytes

2024-11-20 14:09 UTC, kdvalin requested changes

2024-11-20 14:09 UTC, kdvalin commented on unit_conversion
> +# In case of throughput, that will be bytes.
Would it be possible to allow a second arg to act as the `to` unit?  This will make it more flexible for future usage.

2024-11-20 14:22 UTC, malucius-rh commented on unit_conversion
> +		;;
Kilobytes and kibibytes aren't the same thing (same for mega/mebi and giga/gibi). The SI units are base 10 and the IEC units are base 2.

2024-11-20 14:23 UTC, malucius-rh commented on unit_conversion
> +# In case of throughput, that will be bytes.
Agree with @kdvalin , especially since while nanoseconds may be fairly future-resistant bytes for throughput is going to make for some very large numbers in charts. What's good for a filesystem test may not be good for a network test.

2024-11-20 16:33 UTC, malucius-rh commented on unit_conversion
> +	echo "	byte, B, Kib, KB, MiB, MB, GiB, GB"
"Kib" should be "KiB" since "B" is byte and "b" is bit.

2024-12-02 15:34 UTC, dvalinrh commented on unit_conversion
> +	echo "	byte, B, Kib, KB, MiB, MB, GiB, GB"
Using the command numfmt for converting from units.   We do not handle the conversion from bits to bytes, but we can add that if desired.

2024-12-02 15:57 UTC, malucius-rh commented on unit_conversion
> +	echo "	byte, B, Kib, KB, MiB, MB, GiB, GB"
That's not what I was saying. I'm saying "Kib" is wrong when talking about bytes. It's probably just a typo, but it's a meaning-changing typo.

2024-12-02 15:59 UTC, dvalinrh commented on unit_conversion
> +	echo "	byte, B, Kib, KB, MiB, MB, GiB, GB"
Ok, with the new code, and using numfmt, this all goes away

2024-12-10 13:30 UTC, dvalinrh commented on convert_numeric
> +if [ $? -ne 0 ]; then
looks wrong,  move after opt

2024-12-10 13:36 UTC, dvalinrh commented on convert_numeric
> +				exit -1
Remove exit -1, gets handled later.

2024-12-10 13:37 UTC, kdvalin requested changes

2024-12-10 13:37 UTC, kdvalin commented on convert_numeric
> +	echo "--unit <u>: Unit of value or to be converted."
```suggestion
	echo "--unit <u>: Unit of value to be converted."
```

2024-12-11 15:28 UTC, kdvalin requested changes

2024-12-11 15:28 UTC, kdvalin commented on convert_numeric
> +	echo "1000000000ns
```suggestion
	echo "1000000000ns"
```

Missing closing quote

2024-12-12 18:18 UTC, kdvalin requested changes
I think there's a better way to differentiate between time conversion and normal unit conversion than what the running script name is.

2024-12-12 18:18 UTC, kdvalin commented on convert_numeric
> +	echo "1000000000ns"
Wouldn't this be confusing to see 2 different script names within the same usage message?

I think adding a `--time` arg would make more sense then changing modes based off the script basename.

2024-12-12 18:18 UTC, kdvalin commented on convert_numeric
> +	echo "--cnv_unit <u>: Unit to convert to."
Maybe use `--to-unit` and `--from-unit` here, makes it more clear what the script will be doing.

2025-01-07 13:36 UTC, dvalinrh commented on convert_val
> +	echo ""
Missing usage timeval option.

2025-01-07 19:41 UTC, kdvalin requested changes
Minor nits

2025-01-07 19:41 UTC, kdvalin commented on convert_val
> +	echo "If --value, --from_unit and --cnvt unit is passed, then the program will convert <value><unit> to"
```suggestion
	echo "If --value, --from_unit and --to_unit is passed, then the program will convert <value><unit> to"
```

2025-01-07 19:41 UTC, kdvalin commented on convert_val
> +	echo "If --value and --from_unit, program returns the value in the base unit."
Specify the base units, what are they?

2025-01-07 19:41 UTC, kdvalin commented on convert_val
> +# Copyright (C) 2024  David Valin dvalin@redhat.com
```suggestion
# Copyright (C) 2025  David Valin dvalin@redhat.com
```

2025-01-08 12:05 UTC, dvalinrh commented on convert_val
> +	echo "If --value, --from_unit and --cnvt unit is passed, then the program will convert <value><unit> to"
Fixed

2025-01-08 12:05 UTC, dvalinrh commented on convert_val
> +# Copyright (C) 2024  David Valin dvalin@redhat.com
Fixed.

2025-01-08 14:31 UTC, kdvalin requested changes

2025-01-08 14:31 UTC, kdvalin commented on convert_val
> +	echo "If --value and --from_unit, program returns the value in the base unit."
I think I wasn't clear, if `--value` and `--from_unit` are specified, what unit does it return?  What about if `--time_val` is specified, does that change anything?

2025-01-08 14:31 UTC, kdvalin commented on convert_val
> +	echo "If --value and --from_unit, program returns the value in the base unit."
Listing out all the scaling units is a bit excessive

2025-01-08 15:11 UTC, dvalinrh commented on convert_val
> +	echo "If --value and --from_unit, program returns the value in the base unit."
So what you are looking for is the defaults, right?

2025-01-08 15:15 UTC, kdvalin commented on convert_val
> +	echo "If --value and --from_unit, program returns the value in the base unit."
Essentially yes, if `--to_unit` is not specified, what unit does it convert to?

2025-01-08 15:49 UTC, dvalinrh commented on convert_val
> +	echo "If --value and --from_unit, program returns the value in the base unit."
Updates as requested made.

2025-01-14 15:58 UTC, merged